Added recorded and an example (to be removed)
napalm-automation/napalm-base pull request #296
Opened 2017-08-07 22:39 UTC by dbarrosop

2017-08-07 22:50 UTC, dbarrosop commented
@ubaumann @mirceaulinic @ktbyers thoughts?

2017-08-08 06:39 UTC, ubaumann commented
With this approach we could address the 'more verbose logging' issue as well: https://github.com/napalm-automation/napalm-base/issues/272 https://github.com/napalm-automation/napalm-base/issues/273

I will look deeper in the code asap

2017-08-08 08:58 UTC, ubaumann commented
My findings so far:

 - debugging will be harder new newbie. (Debug pointer is jumping around thru `recoder` function)
 - We should not create the real object in 'replay' mode. Netmiko tries to establish the connection in the constructor and will fail
```
...
  File "/home/ubaumann/napalm-base/napalm_base/recorder.py", line 57, in __init__
    self.device = cls(*args, **kwargs)
  File "/home/ubaumann/.virtualenvs/napalm_base/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/ubaumann/.virtualenvs/napalm_base/lib/python2.7/site-packages/netmiko/base_connection.py", line 150, in __init__
    self.establish_connection()
  File "/home/ubaumann/.virtualenvs/napalm_base/lib/python2.7/site-packages/netmiko/base_connection.py", line 506, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 127.0.0.1:123
```
 
With the files and the count number, the order of commands can't be changed. So, every workflow needs a separate record. I would like to have a more flexible way. For example creating a YAML file with the function name and the arguments, so the the recording can be reused. I know the file could get big.
```
send_command:
  - 'show version': 'asdfasdfasdfasdf'
  - 'show interface': 'asdfasdfasdfasdf'
enable: ''
```
Advantages from my point of view:
 - More readable then with `pickle.dumps`
 - Reusable / more flexible
 - Just one file to handel for each wrapped object


Recordings make it easy to test against different OS versions

2017-08-08 09:03 UTC, mirceaulinic commented on napalm_base/recorder.py
> +    with open(os.path.join(cls.path, filename), 'w') as f:
This should scream as a resource leakage.

2017-08-08 09:03 UTC, mirceaulinic commented on napalm_base/recorder.py
> +    filename = "{}.{}".format(func.__name__, cls.current_count)
I'd probably use the FQDN rather than a spin number, so you can have a better understanding on what commands have been executed where.

2017-08-08 09:04 UTC, mirceaulinic commented on napalm_base/recorder.py
> +    with open(os.path.join(cls.path, filename), 'w') as f:
Also, this is saving a file under the Python sys paths - not good.

2017-08-08 09:07 UTC, mirceaulinic reviewed
I kinda like the idea, but if I'd compare the benefits vs. complexity + risks and environment exposure, I find there's not much real value added.

There's also the long-vehiculated argument: this should probably happen in a higher level tool, napalm is just a library :]

2017-08-08 09:26 UTC, mirceaulinic commented
> With the files and the count number, the order of commands can't be changed. So, every workflow needs a separate record. I would like to have a more flexible way. For example creating a YAML file with the function name and the arguments, so the the recording can be reused. I know the file could get big.

Yes, I believe this is _way_, _way_, beyond the goals of NAPALM - as @dbarrosop likes to say everytime, "napalm is a library, it's not a tool.", so this implementation, from any perspective, I believe it doesn't really fit into this definition.

2017-08-08 09:40 UTC, dbarrosop commented on napalm_base/recorder.py
> +    with open(os.path.join(cls.path, filename), 'w') as f:
> This should scream as a resource leakage

Care to elaborate?

> Also, this is saving a file under the Python sys paths (where the lib is installed) - not good.

path is specified by the user. Not sure what you mean.

2017-08-08 09:42 UTC, dbarrosop commented on napalm_base/recorder.py
> +    filename = "{}.{}".format(func.__name__, cls.current_count)
path is specified by the user via `optional_arg["recorder_path"]`, if you want to use hostname, use it. You are not limited by anyone making any decissions for you. The code you are pointing out is just a deterministic way of finding the order of the calls.

2017-08-08 09:55 UTC, dbarrosop commented
> We should not create the real object in 'replay' mode

I agree. That's certainly an easy bug to fix.

> With the files and the count number, the order of commands can't be changed

That's the point. This is a recorder/replayer.

> I kinda like the idea, but if I'd compare the benefits vs. complexity + risks and environment exposure, I find there's not much real value added.

Complexity, less than what we have today. Benefits of having this between each driver and the underlying class (netmiko, pyeapi, etc):

1. Test cases are easily recorded. Just run the test against a real device in recording mode and you are done.
2. With these 60 lines of code, including whitespaces and comments, you can say goodbye to all the mocking code we have today, which is a lot and vendor dependent; MockDriver, FakeEOS, FakeJunos, Fakeblah, all gone.
3. Debugging, something breaks? Just enable recording mode and check what's happening, the scenario can even be shared on an issue/branch/PR for us to debug and fix.
4. Compliance, I am sure compliance people would like it.

An alternative to the "pass" behavior would be to call the class directly without the wrapper so the default behavior wouldn't change at all. So on the drivers we would have:

```
                if self.recorder_mode == "pass":
                    self.device = pyeapi.client.Node(connection, enablepwd=self.enablepwd)
                else:
                      self.device = napalm_base.recorder.Recorder(pyeapi.client.Node,
                                                               recorder_options=self.recorder_options,
                                                              connection=connection,
                                                            enablepwd=self.enablepwd)
```

Or something like that

2017-08-09 07:37 UTC, itdependsnetworks commented
My take: 

- More debugging is helpful. Have run into issues that are masked
- Was looking for the record feature of this. It is helpful to see the raw data and be able to keep it for historical purposes
- Can use the cli to backup commands not in data model. e.g. have a requirement to log: `sh   hardware internal errors module 1 \| diff \| i crc`
- If we add a way to anonymize confidential data (e.g. IP, descriptions, etc..) potentially make it easier for users to contribute mock data. 

IMHO unless this introduced an unnecessary amount of work and future burden I see it as clear net positive.

2017-08-10 18:47 UTC, ktbyers commented
@itdependsnetworks Can you elaborate on this statement?

```
Can use the cli to backup commands not in data model. e.g. have a requirement to log: sh hardware internal errors module 1 \| diff \| i crc
```

I think we should use probably use JSON or YAML to save data instead of pickle. 

I like the general idea.

2017-08-11 07:07 UTC, dbarrosop commented
> I think we should use probably use JSON or YAML to save data instead of pickle.

Problem with YAML/JSON is that it becomes a problem when the method returns pythons objects. For example, a method might return `None` or `True`, an `Exception` or even a custom object, and those don't translate well to structured data. But I will do some tests and see what happens.

2017-08-11 16:31 UTC, ktbyers commented
If we use Pickle, then we won't be able to accept data from anyone we don't trust...as they could totally mess us over (like embed a system calls inside the pickle file).

2017-08-16 17:40 UTC, dbarrosop commented
> then we won't be able to accept data from anyone we don't trust

As discussed via other channels. I think you are right and I will look into that. The main issue is that not all calls might return structured but some "bare" object like a string or an Exception but that can be treated.

> mirceaulinic raised the concern that the recorder might break things if a method changes how things are retrieved

That is very much correct so we will do two things:

1.  Make clear in the documentation that the recorder is mostly for internal purposes and that they are free to use it but without guarantees.
2. We will add some metadata when recording so if we break something we know how and when it was recorded. For example, we could add the date and all the napalm libraries installed with their version at the time of the recording.

2017-08-17 06:36 UTC, dbarrosop commented
Regarding the metadata, now it adds a `metadata.yaml` file with the following contents:

```
(napalm) ➜  napalm-base git:(recorder) ✗ cat test_recorder/metadata.yaml
date: 2017-08-16 19:57:11.194889
napalm_version:
- napalm-ansible==0.7.0
- napalm-base==0.24.3
- napalm-eos==0.6.0
- napalm-fortios==0.4.0
- napalm-ios==0.7.0
- napalm-iosxr==0.5.4
- napalm-junos==0.12.0
- napalm-nxos==0.6.0
- napalm-panos==0.4.0
- napalm-pluribus==0.5.1
- napalm-ros==0.2.2
- napalm-vyos==0.1.3
- napalm==1.2.0
```

2017-08-17 11:05 UTC, mirceaulinic requested changes
I have a comment regarding the dependency. Please let's discuss before pushing this further.

2017-08-17 11:05 UTC, mirceaulinic commented on requirements.txt
> +camel
If we are anyway adding another dependency for serialization, why not use something widely adopted like [msgpack](http://msgpack.org/)?

Whatever would be the extra package, I dislike very much the idea of having a dependency for a feature I know for sure I'll never use.

2017-08-17 11:10 UTC, dbarrosop commented
@ktbyers @mirceaulinic latest update replaces pickle with `Camel`, which builds on top of `pyyaml` to provide a safe mechanism to serialize/deserialize custom objects.

I tried pyyaml pickle-like behavior but it turns out is as unsafe as `pickle` itself and also not very reliable as it fails to understand how the constructor of the classes work.

I recommend reading this if you have the time/energy:

https://eev.ee/blog/2015/10/15/dont-use-pickle-use-camel/

If you are happy with this I will remove all the testing stuff I added and merge. Then I will quickly integrate it with the `napalm` cli tool so users can start recording with it.

2017-08-17 11:15 UTC, dbarrosop commented on requirements.txt
> +camel
"MessagePack is an efficient binary serialization format. It's like JSON. but fast and small."

So a few reasons:

1. We don't want binary, we want something secure that humans can look at.
2. Camel is is a tiny library that builds on top of pyyaml, which we already have.
3. `msgpack` is huge and include even more C extensions.

2017-08-17 11:16 UTC, mirceaulinic commented
@dbarrosop - you may have missed my review.

I disagree on using an obscure library that gained less interest than naplam (i.e. https://github.com/eevee/camel has exactly 7 followers), rather than a very well known and widely adopted msgpack (also very well know for its speed).

Also, it's very bizzare that the sole resource I was able to find about this camel is the blog post you pointed out... written by its maintainer and one of the **4** contributors.

2017-08-17 11:24 UTC, dbarrosop commented
> I disagree on using an obscure library that gained less interest than naplam (i.e. https://github.com/eevee/camel has exactly 7 followers)

Are we measuring now usefulness by number of followers? Doesn't make much sense IMHO.

> rather than a very well known and widely adopted msgpack (also very well know for its speed

I can write myself what camel does as it's just a framework on top of pyyaml, which seems unnecessary to write as someone else did it already, but as I mentioned in the other comment, `msgpack` is way overkill and doesn't do exactly what we want.

2017-08-17 11:26 UTC, mirceaulinic commented
Huge? :-/

```bash
(david-learns) mircea@ip-172.31.11.15 ~
> time pip install msgpack-python
Collecting msgpack-python
  Downloading msgpack-python-0.4.8.tar.gz (113kB)
    100% |████████████████████████████████| 122kB 2.2MB/s
Building wheels for collected packages: msgpack-python
  Running setup.py bdist_wheel for msgpack-python ... done
  Stored in directory: /home/mircea/.cache/pip/wheels/2c/e7/e7/9031652a69d594665c5ca25e41d0fb3faa024e730b590e4402
Successfully built msgpack-python
Installing collected packages: msgpack-python
Successfully installed msgpack-python-0.4.8

real  0m1.098s
user  0m0.792s
sys 0m0.158s
```

 I certainly don't want camel or whatever _you_ decide you _want_, by default, in NAPALM.

2017-08-17 11:34 UTC, dbarrosop commented
Dude, it's a full blown new serializator/deserializator with it's own C-extenssions that occupies `113kB` compared to a single file that occupies 7kB that doesn't require any C-extensions because it uses `pyyaml` which is already a dependency. So, you can keep your sarcasm and your `david-learn` virtual environment name to yourself because even if you are still not convinced that `msgpack` is a huge dependency, it still doesn't do what we want.

2017-08-17 12:19 UTC, dbarrosop commented
As discussed in slack, will rewrite without dependencies.

2017-12-20 16:01 UTC, closed without merging